### ISSUE TITLE
compatbility with  phono3py-kaccum  is broken when using winger option

### ISSUE THREAD

**Issue by akentphonon** [phonopy/phono3py#100]
Dear developers,

In the development version of phono3py- when using "--wigner" option compatibility with phono3py-kaccum is broken because 'mode_kappa' is no longer printed.

Thanks and Best Regards
Alex kent

**Comment by atztogo** [comment]
`--wigner` is under the development and so not yet supported.

**Comment by atztogo** [comment]
I will close this issue because of the reason above.
