### ISSUE TITLE
"disp_fc3.yaml" was not found.

### ISSUE THREAD

**Issue by haohuaijin** [phonopy/phono3py#111]
**Describe the bug**
when i want to create FORCE_SETS from FORCES_FC3 and phono3py_disp.yaml, i get `"disp_fc3.yaml" was not found.`.

**To Reproduce**
```
(phono3py) [home]$ phono3py --cfs
        _                      _____
  _ __ | |__   ___  _ __   ___|___ / _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ |_ \| '_ \| | | |
 | |_) | | | | (_) | | | | (_) |__) | |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___/____/| .__/ \__, |
 |_|                                |_|    |___/ 
                                       2.3.0

Python version 3.9.12
Spglib version 1.16.1

"disp_fc3.yaml" was not found.
  ___ _ __ _ __ ___  _ __
 / _ \ '__| '__/ _ \| '__|
|  __/ |  | | | (_) | |
 \___|_|  |_|  \___/|_|

```
the FORCES_FC3 and phono3py_disp.yaml is in the current directory

**Comment by atztogo** [comment]
Thanks for your bug report @haohuaijin! I fixed it on the develop branch. Now the support of `disp_*.yaml` files is dropped. Only `phono3py_*.yaml` type file is supported. The default filename is `phono3py_disp.yaml` but you can specify it by `phono3py -c [phono3py-yaml-file-name]` command.

**Comment by haohuaijin** [comment]
Thank you for your reply. The program runs successfully.
