### ISSUE TITLE
pip install phono3py fails because site.cfg not found

### ISSUE THREAD

**Issue by Youjin1985** [phonopy/phono3py#130]
**Check the develop branch**
Report to the combination of the develop branch of phonopy and the develop branch of phono3py.

**Describe the bug**
pip install phono3py fails because site.cfg not found

**To Reproduce**
1. pip install phono3py
2. it fails

creating this file in directory where command runs has no effect

**Comment by atztogo** [comment]
Thanks for your report.
This is related to this issue https://github.com/phonopy/phono3py/issues/99.

**Comment by atztogo** [comment]
I will close this issue because it is solved.
