### ISSUE TITLE
Help: massive number of POSCAR-xxxxx produced by phono3py

### ISSUE THREAD

**Issue by LePingKYXK** [phonopy/phono3py#175]
I want to use the phono3py (version 2.6.0) to calculate the lattice thermal conductivity of the hybrid organic-inorganic perovskite, which has **44 atoms**, belonging to the space group of `Pmma`. After relaxing the structure via VASP, I copied the CONTCAR and rename it as POSCAR into a new directory. Then, I tried the code
```bash
phono3py -d --dim="2 2 2" -c POSCAR
``` 
However, it produced **71907** displacements structure files! I can not imagine how many months the subsequent calculations will finish.

I am new to phono3py. I was wondering if the massive number of POSCAR-xxxxx files is a common occurrence.

---
The POSCAR file is provided below.
```
DJ1L_Pmma
   1.0
     9.0736764969368906    0.0000000000000000    0.0000000000000000
     0.0000000000000000    9.9721293685144623    0.0000000000000000
     0.0000000000000000    0.0000000000000000    8.5241021933268151
H C N I Pb
  24    6    4    8    2
Direct
  0.6588694442733071  0.2599351532526649  0.8572357598090808
  0.8478002732898366  0.8704876068486431  0.6137089531036838
  0.8411305557266929  0.7400648467473351  0.8572357598090808
  0.6521997267101634  0.1295123931513569  0.6137089531036838
  0.3411305557266929  0.2599351532526649  0.1427642401909192
  0.1521997267101634  0.8704876068486431  0.3862910468963162
  0.1588694442733072  0.7400648467473351  0.1427642401909192
  0.3478002732898366  0.1295123931513569  0.3862910468963162
  0.3411305557266929  0.7400648467473351  0.1427642401909192
  0.1521997267101634  0.1295123931513569  0.3862910468963162
  0.1588694442733072  0.2599351532526649  0.1427642401909192
  0.3478002732898366  0.8704876068486431  0.3862910468963162
  0.6588694442733071  0.7400648467473351  0.8572357598090808
  0.8478002732898366  0.1295123931513569  0.6137089531036838
  0.8411305557266929  0.2599351532526649  0.8572357598090808
  0.6521997267101634  0.8704876068486431  0.6137089531036838
  0.6524516836056640  0.0000000000000000  0.8698486227754814
  0.8475483163943360  0.0000000000000000  0.8698486227754814
  0.3475483163943360  0.0000000000000000  0.1301513772245186
  0.1524516836056640  0.0000000000000000  0.1301513772245186
  0.7500000000000000  0.3340324783940282  0.7108608812789095
  0.7500000000000000  0.6659675216059717  0.7108608812789095
  0.2500000000000000  0.3340324783940282  0.2891391187210905
  0.2500000000000000  0.6659675216059717  0.2891391187210905
  0.7500000000000000  0.8751939055699482  0.6893422642587961
  0.7500000000000000  0.1248060944300518  0.6893422642587961
  0.2500000000000000  0.8751939055699482  0.3106577357412039
  0.2500000000000000  0.1248060944300518  0.3106577357412039
  0.7500000000000000  0.0000000000000000  0.7929738492951516
  0.2500000000000000  0.0000000000000000  0.2070261507048484
  0.7500000000000000  0.7483134396959018  0.7844534705212637
  0.7500000000000000  0.2516865603040982  0.7844534705212637
  0.2500000000000000  0.7483134396959018  0.2155465294787363
  0.2500000000000000  0.2516865603040982  0.2155465294787363
  0.2500000000000000  0.1864934119484717  0.7888730255668756
  0.2500000000000000  0.8135065880515283  0.7888730255668756
  0.7500000000000000  0.1864934119484717  0.2111269744331244
  0.7500000000000000  0.8135065880515283  0.2111269744331244
  0.5000000000000000  0.5000000000000000  0.0000000000000000
  0.0000000000000000  0.5000000000000000  0.0000000000000000
  0.5000000000000000  0.5000000000000000  0.5000000000000000
  0.0000000000000000  0.5000000000000000  0.5000000000000000
  0.2500000000000000  0.5000000000000000  0.7502717802102575
  0.7500000000000000  0.5000000000000000  0.2497282197897425
```

**Comment by aronwalsh** [comment]
I confirm that is a common occurrence for hybrid organic-inorganic compounds where molecules lower the crystal symmetry. For example, we needed > 40,000 displacements for [CH3NH3PbI3](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.94.220301). 

Losening the symmetry tolerance or shortening the cutoff radius may help, but need to be checked, and I would suggest Phono3py is not the optimal solution for such cases. Sampling procedures in codes like ALAMODE or TDEP will be more efficient than calculating all of the individual displacements.

**Comment by atztogo** [comment]
@LePingKYXK, github issue is mainly used for the code development discussion. So for the usage, please send your question to the phonopy mailing list.

Thanks @aronwalsh for answering. As @aronwalsh, phono3py is not focusing on this point since there are many other good codes about it. A list of software packages related to anharmonic phonon calculation is found at https://hiphive.materialsmodeling.org/related_codes.html.

**Comment by LePingKYXK** [comment]
Thank you @aronwalsh and @atztogo for your kind reply. I will check the list of related software, especially the ALAMODE or TDEP.

**Comment by atztogo** [comment]
I recommend hiphive, too. See https://hiphive.materialsmodeling.org/advanced_topics/self_consistent_phonons.html. I close this issue by this.
