### ISSUE TITLE
Feature request for boundary scattering model

### ISSUE THREAD

**Issue by akentphonon** [phonopy/phono3py#185]
Dear Dr. Togo,

I was wondering in the future if it will be possible to allow for several values for length L in boundary scattering model. i.e
--bmfp 1 10 50 100 1000 etc....

something like this exists with --sigma options. This will be helpful when fitting the results with the available experimental data as a function of grain size. 

May thanks
Alex

**Comment by atztogo** [comment]
This will change the data structure of hdf5 file, so the impact is large. But without  this feature requeested, you can compute with different boundary scattering model in the following way,

1. --write-gamma
2. --read-gamma and --boundary-mfp 1
3. --read-gamma and --boundary-mfp 10

...

**Comment by akentphonon** [comment]
Thank you. This works perfectly. I will close this now.

Thanks,
Alex
