### ISSUE TITLE
Converting phono3py's generated force constants into ShengBTE inputs

### ISSUE THREAD

**Issue by Amrt4696** [phonopy/phono3py#235]
Dear Professor,

I want to convert phono3py's generated force constants into ShengBTE inputs, I saw an issue there you have provided a git link to do that, but that link is no longer working. Can you please help me out?

Thanks,
Amrendra

**Comment by atztogo** [comment]
Please ask your question in the phonopy mailing list. See https://phonopy.github.io/phono3py/#mailing-list
