### ISSUE TITLE
Non Gamma point FC3 calculation at unitcell level 

### ISSUE THREAD

**Issue by rfhari** [phonopy/phono3py#282]
Hello, I'm relatively new to using phono3py and I'm interested in calculating third-order force constants (FC3) using DFT with the VASP interface. This [tutorial](https://github.com/phonopy/phono3py/tree/develop/example/AlN-LDA) was helpful in understanding the process. However, I was wondering if, similar to thirdorder.py, phono3py can calculate FC3 at non-Gamma points at a unit cell level. 

Any guidance on this would be greatly appreciated.

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.
