### ISSUE TITLE
Sequential atom index in third order force constants

### ISSUE THREAD

**Issue by rfhari** [phonopy/phono3py#283]
Hello, 

I'm not sure if this is the right place to post this question. If not, please let me know. 

I’m relatively new to using phono3py and am interested in calculating third-order force constants (FC3) with DFT through the VASP interface. Currently, I’m working on AlN and using a 3x3x2 supercell to compute FC3. After converting to ShengBTE format (using [hiphive](https://hiphive.materialsmodeling.org/advanced_topics/force_constants_io.html#conversion-betweeen-shengbte-and-phono3py)), I noticed that the sequential atom index (the fourth line of every FC block) indicates atoms beyond the AlN unit cell. I’m wondering if there’s a tool/flag (either within or outside phono3py) that can map the atoms back to the unit cell by correspondingly changing the cartesian coordinates in the second and third lines of each FC block. 

This mapping would be particularly useful as I plan to study GaN and eventually AlGaN alloys using almabte, which requires force constants in the mapped unit cell format. Any guidance on this would be greatly appreciated.

**Comment by atztogo** [comment]
Here is not the right place.

**Comment by atztogo** [comment]
I will close this issue.
