### ISSUE TITLE
magetic structure in phono3py

### ISSUE THREAD

**Issue by akentphonon** [phonopy/phono3py#38]
Dear Togo  Sensei,

This is more of query not an issue with phono3py.  I was wondering if it possible to include symmetry breaking due to non-zero magnetic moments  while creating displacements in phono3py. The crystal i am investigating in AFM type, and  at least within phonopy I see that inducing magnetic lowers the overall symmetry of the cell.

Thanks
Alex

PS. Sorry about posting this here.  I am having trouble with my email.

**Comment by atztogo** [comment]
I've never tried, so I realized it is not supported by the phono3py command. But I think it should work in the API level, i.e., just there is no route to pass magmom information to phono3py command. Do you have an example of crystal structure with magnetic moments?

**Comment by akentphonon** [comment]
Togo Sensei, Thank you for your response.  

I was hoping to do some magnetic structure like MnTe, and MnSe..  But now reading the lietraure carefully it seems that in these structures magentic moments can be canted (non collinear), which I think cannot be handled within phonopy ( also the DFT runs for these would be changeling).

For collinear magnetic structures, I think phonopy works well as long as I specify a unit-cell with correct magnetic ordering (via magmom).  I think the same way it done for phno3py as well, I will take a look for possibility of doing it within API.

Once I have  working example ready, I will share it. I will close this for now.


Thanks and Regards
Alex

**Comment by atztogo** [comment]
OK, I see. I implemented non-collinear type symmetry treatment in spglib. So maybe some day in the future.
