### ISSUE TITLE
slow speed in generating displacements

### ISSUE THREAD

**Issue by alinelena** [phonopy/phono3py#42]
I am not really sure this is a bug or not.

I try to generate displacements in a relatively big cells 100-400 atoms, one must assume no symmetry.
I noticed it takes really long, even if I specify --cutoff-pair  --cutoff-fc3

I did not do a systematic measuring of time but seems using cutoffs does not affect generation time but only the number of displacements.
Am I wrong?

**Comment by atztogo** [comment]
Could you tell How I can reproduce this problem?

**Comment by alinelena** [comment]
here is some data
Python version 3.8.5
Spglib version 1.16.1



cutoff

phono3py -d --dim='1 1 1' --cutoff-pair 4.24 --cutoff-fc3 2.12 


head disp_fc3.yaml
natom: 106
num_first_displacements: 636
cutoff_distance: 4.240000
num_second_displacements: 404496
num_displacements_created: 57300
duplicates:


time: 01:15:14 



no cutoff

phono3py -d --dim='1 1 1'

head disp_fc3.yaml
natom: 106
num_first_displacements: 636
num_second_displacements: 404496
num_displacements_created: 405132
duplicates:

time:1:43:39


I would expect using the cutoff to cut the generation time seriously, the difference I think is largely due to writing all the data on the parallel file system I think.

the poscar if you want to look at it is in here
https://github.com/WMD-group/VMOF/blob/master/STRUCTURE_FILES/MOF-5/POSCAR

**Comment by atztogo** [comment]
Thanks.
I found this method is very slow.
https://github.com/phonopy/phono3py/blob/545af589388e25b51bcac6d3a8f61ecd7e70a002/phono3py/phonon3/displacement_fc3.py#L335

Commenting out this method call (lines 73 and 79), 
```
% phono3py -d --dim='1 1 1' --cutoff-pair 4.24 --cutoff-fc3 2.12
```
finished in about 2 mins including writing out files on my macbook pro.
The method `_find_duplicates` finds the same supercells (sets of two displacements are same) but from using command line, almost no effect. So you can disable `_find_duplicates`.

Clearly the algorithms of `_find_duplicates` is not well written. Lines 353-354 means O(n^2) and n is the number of displacements. I will consider if this feature should be kept or not, or if the algorithm will be improved. But, first I will try the later.

**Comment by atztogo** [comment]
I made some update at 9a8d107 to fix this issue. Now I expect your command will finish in a few minitues though it may depend on the file I/O speed. The code is in develop branch.

**Comment by alinelena** [comment]
thanks I will give it a try later today.

**Comment by alinelena** [comment]
Indeed I tested things look much better now.

Alin

**Comment by atztogo** [comment]
I will fix this issue because this issue is considered fixed.
