### ISSUE TITLE
phono3py-kaccum error importing grid methods

### ISSUE THREAD

**Issue by NightlyJonny** [phonopy/phono3py#45]
# System info
Running `phonopy 2.10.0` and `phono3py 1.22.3` on Arch Linux.

# Bug
The `phono3py-kaccum` script doesn't seem to work in the last versions of phono3py. As far as I can tell it still tries to import some grid-related methods from `triplets.py` that have been moved to another python module. Simply importing them from `grid.py` does not solve the problem.
```
Traceback (most recent call last):
  File "/usr/bin/phono3py-kaccum", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/user/phono3py/scripts/phono3py-kaccum", line 8, in <module>
    from phono3py.phonon3.triplets import (get_ir_grid_points,
ImportError: cannot import name 'get_ir_grid_points' from 'phono3py.phonon3.triplets' (/home/user/phono3py/phono3py/phonon3/triplets.py)
```

# To Reproduce
Running `phono3py-kaccum` at the end of the [Si-PBEsol](https://github.com/phonopy/phono3py/tree/develop/example/Si-PBEsol) example (or I guess with any input files).

I apologize if this issue is not relevant anymore. If so, is there a newer way to extract the cumulative thermal conductivity?
Thank you in advance.

**Comment by atztogo** [comment]
Thanks for your report @NightlyJonny. Maybe you use develop branch?

**Comment by NightlyJonny** [comment]
Of course, I was indeed using the develop branch. After switching to the master branch everything works as intended.

Thank you very much for your help and for the quick response.

**Comment by atztogo** [comment]
Thanks to this issue, I could realize that `phono3py-kaccum` is broken in develop branch. I will fix it but not very soon because phono3py is currently under the big update.
