### ISSUE TITLE
simulating antiferromagetic structure in phono3py

### ISSUE THREAD

**Issue by akentphonon** [phonopy/phono3py#53]
Dear developers,

I am currently studying different magnetic orderings of a Cr-based material.  To model AFM ground state, I use a fake chemical species to differentiate between Cr spin up and spin down atoms.  This is needed for phonopy/phono3py to detect the low symmetry of the AFM phase due to constraint on spin.  For force calculations I am using proper magmom tags to enforce AFM ordering.
 
I have two questions on this:
1. Is this a reasonable approximation for getting IFCs of AFM materials.
2. I guess the symmetry will also affect the q-points used in lattice thermal conductivity in phonop3py.  Should I do same trick will phono3py. I was thinking of supplying mass and mass-variances manually to account for fake elements in the structure.

Your thoughts/suggestion on this will be helpful.

PS> I know that we can pass magmom tag in phonopy to set the magnetic ordering for displaced super-cells. Is this possible in phono3py also?

Best,
Alex

**Comment by atztogo** [comment]
@akentphonon, I'm sorry for my late reply. I was busy.

If you assume those magnetic moments have the same values for respective fake atoms, I think it should almost work. But some symmetry that allows all spins flip may be missing.

In phono3py, magmom tag doesn't work currently. I will try to make it work.

**Comment by akentphonon** [comment]
Thank you for response.  My test with fake atom method give satisfactory results. I will close this for time being.

Thanks,
Alex

**Comment by atztogo** [comment]
Yes, I think your approach works.

I added magmom support for phono3py though not yet tested carefully. If you are interested in it, it is in the develop branch, for which, you also need the phonopy's latest develop branch.

**Comment by akentphonon** [comment]
Thank you very much. I will test the magmom options from the develop branch. 

If I find any bugs I will report them here.

Thanks again for your time.

Best,
Alex

**Comment by akentphonon** [comment]
I tested the magmom option in the develop branch - it works fine. 

Thanks a lot for your help.
