### ISSUE TITLE
Phono3py installation issues

### ISSUE THREAD

**Issue by constance671** [phonopy/phono3py#81]
Dear Prof. Togo

After installing phono3py using conda I get this issue when I try to use it:

File "path/phono3py/cui/phono3py_script.py", line 498, in get_cell_info
    cell_info = collect_cell_info(
TypeError: collect_cell_info() got an unexpected keyword argument 'symprec'

Do you have any suggestion?
Thanks a lot!

**Comment by atztogo** [comment]
Here is for the code development, and I doubt your installation. So please send your question to the phonopy mailing list.

**Comment by ybC007** [comment]
Is the problem solved? I have met the same problem and don't know the reason.

**Comment by atztogo** [comment]
We are working.

**Comment by atztogo** [comment]
Now it's fixed.
