### ISSUE TITLE
index # is out of bounds for axis 0 with size #

### ISSUE THREAD

**Issue by sinazadeh** [phonopy/phono3py#82]
After setting cutoff_pair_distance, index # is out of bounds for axis 0 with size # error raises.

```
phono = Phono3py(
        unitcell=atoms,
        supercell_matrix=[2,2,2],
        primitive_matrix=structure[1])

phono.generate_displacements(cutoff_pair_distance=3.0)
...
...
phono.forces = np.array(forces_lst)
```

![image](https://user-images.githubusercontent.com/63080674/156278551-5c96a571-5311-404e-8a7a-5d93dab962b4.png)

**Comment by atztogo** [comment]
Sorry, I can't understand.

**Comment by CCSun21** [comment]
@sinazadeh  Hello, I have encountered the same problem. May I ask how did you solve it finally?

**Comment by atztogo** [comment]
First of all, I don't recommend you to use `generate_displacements(cutoff_pair_distance=3.0)`. What I recommend is the combination of random displacements and force constants calculation with cutoff-pair, see the note at https://phonopy.github.io/phono3py/cutoff-pair.html . I want to make it as deprecated.

About your question, my guess is as follows:

The array of forces should have the same shape as `phonon.displacements.shape`. You used `phonon.generate_displacements(cutoff_pair_distance=3.0)`. You can see the dataset by

```
phonon.dataset
```

For each supercell of a pair displacement, there is a flag `included`. When True, you have to run supercell force calculations. When False, you have to set some values (e.g., `np.zeros((natoms_in_supercell, 3))`) as dummy supercell forces.

**Comment by CCSun21** [comment]
@atztogo Thank you very much! Adding dummy supercell forces has solved the problem.
